name: Weekly Secrets Sync

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  sync-secrets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Sync GitHub Secrets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run sync-github-secrets
      
      - name: Install Supabase CLI
        run: |
          curl -fsSL https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz | tar -xz
          sudo mv supabase /usr/local/bin/
      
      - name: Sync Supabase Secrets
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: npm run sync-supabase-secrets
      
      - name: Validate Secrets
        run: |
          npm run validate-github-secrets
          npm run validate-supabase-secrets
      
      - name: Trigger Supabase Webhook
        run: |
          curl -X POST "${{ secrets.SUPABASE_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{"platform":"both","trigger":"scheduled"}'
